# 3. Convolution Operations with Different Parameters

### Task:
Implement Convolution with Different Stride and Padding.

Write a Python script using NumPy and TensorFlow/Keras to perform convolution on a 5×5 input matrix using a 3×3 kernel with varying parameters.

This task explores how different **stride** and **padding** settings affect the resulting output feature maps using NumPy and TensorFlow/Keras.


In [5]:
# Import NumPy for creating and working with the input matrix
import numpy as np

# Import TensorFlow to perform convolution operations
import tensorflow as tf


# 1. Define the following 5×5 input matrix:

# Create the 5x5 input matrix
input_matrix = np.array([
    [1,  2,  3,  4,  5],
    [6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
], dtype=np.int32)

# Display the matrix to verify that it was created correctly
print("5x5 Input Matrix:")
print(input_matrix)

# Confirm the dimensions of the input.
print("\nInput matrix shape:", input_matrix.shape)

5x5 Input Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Input matrix shape: (5, 5)


In [4]:
# 2. Define the following 3×3 kernel:

# Create the 3×3 kernel.
kernel_ = np.array([
    [0,  1,  0],
    [1,  -4,  1],
    [0, 1, 0]
], dtype=np.int32)

# Display the kernel to verify that it was created correctly
print("3x3 Kernel:")
print(kernel_)

# Confirm the dimensions of the kernel.
print("\nKernel shape:", kernel_.shape)

3x3 Kernel:
[[ 0  1  0]
 [ 1 -4  1]
 [ 0  1  0]]

Kernel shape: (3, 3)


In [6]:
# 3. Perform convolution operations with different strides and padding

# Convert the original integer matrices to float32 because TensorFlow performs the convolution using floating-point tensors.
input_tensor = tf.cast(input_matrix, tf.float32)
kernel_tensor = tf.cast(kernel_, tf.float32)

# Reshape the 5x5 input into the 4D format required by tf.nn.conv2d:
# [batch, height, width, channels] = [1, 5, 5, 1].
input_tensor = tf.reshape(input_tensor, [1, 5, 5, 1])

# Reshape the 3x3 kernel into TensorFlow's required filter format:
# [height, width, input_channels, output_channels] = [3, 3, 1, 1].
kernel_tensor = tf.reshape(kernel_tensor, [3, 3, 1, 1])


# Stride = 1, Padding = 'VALID'
# VALID adds no padding, so the filter operates only where the complete 3x3 kernel fits inside the input.
output_valid_s1 = tf.nn.conv2d(
    input_tensor, kernel_tensor, strides=1, padding="VALID"
)

# Stride = 1, Padding = 'SAME'
# SAME adds padding around the input as needed to preserve the spatial size when the stride is 1.
output_same_s1 = tf.nn.conv2d(
    input_tensor, kernel_tensor, strides=1, padding="SAME"
)

# Stride = 2, Padding = 'VALID'
# The filter moves two positions at a time with no padding.
output_valid_s2 = tf.nn.conv2d(
    input_tensor, kernel_tensor, strides=2, padding="VALID"
)

# Stride = 2, Padding = 'SAME'
# Padding is added, but the stride of 2 still causes the output to be smaller because the filter moves two positions at a time.
output_same_s2 = tf.nn.conv2d(
    input_tensor, kernel_tensor, strides=2, padding="SAME"
)

In [9]:
# 4. Print the output feature maps for each case.

# TensorFlow stores the convolution result in 4D format: [batch, height, width, channel].
# Since we have only one input and one channel, [0, :, :, 0] selects the complete height and width (:, :) of the first input
# and first channel, leaving only the 2D feature map.

print("Output Feature Map for Stride = 1, Padding = 'VALID'")
print(output_valid_s1[0, :, :, 0].numpy())

print("\nOutput Feature Map for Stride = 1, Padding = 'SAME'")
print(output_same_s1[0, :, :, 0].numpy())

print("\nOutput Feature Map for Stride = 2, Padding = 'VALID'")
print(output_valid_s2[0, :, :, 0].numpy())

print("\nOutput Feature Map for Stride = 2, Padding = 'SAME'")
print(output_same_s2[0, :, :, 0].numpy())

Output Feature Map for Stride = 1, Padding = 'VALID'
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Output Feature Map for Stride = 1, Padding = 'SAME'
[[  4.   3.   2.   1.  -6.]
 [ -5.   0.   0.   0. -11.]
 [-10.   0.   0.   0. -16.]
 [-15.   0.   0.   0. -21.]
 [-46. -27. -28. -29. -56.]]

Output Feature Map for Stride = 2, Padding = 'VALID'
[[0. 0.]
 [0. 0.]]

Output Feature Map for Stride = 2, Padding = 'SAME'
[[  4.   2.  -6.]
 [-10.   0. -16.]
 [-46. -28. -56.]]
